# Generated by Django 2.1 on 2018-09-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='nopicture/none.gif', max_length=255, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
